# Generated by Django 4.2 on 2023-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('tip', models.TextField(blank=True, verbose_name='Подсказка')),
                ('solve', models.TextField(blank=True, verbose_name='Решение')),
                ('reply', models.TextField(blank=True, verbose_name='Решение')),
                ('themes', models.TextField(verbose_name='Категории')),
                ('difficulty', models.CharField(max_length=10, verbose_name='Сложность')),
                ('classes', models.CharField(max_length=20, verbose_name='Сложность')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
